dcurator/accountapp/urls.py
from accountapp.views import hello_world, AccountCreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = "accountapp"
urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
]

dcurator/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accountapp.urls')),
  
]

dcurator/accountapp/models.py
from django.db import models

class HelloWorld(models.Model):
    text = models.CharField(max_length=255,null=False)

dcurator/accountapp/views.py
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse_lazy
from accountapp.models import HelloWorld
from django.shortcuts import render
from accountapp.models import HelloWorld
from django.urls import reverse
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

def hello_world(request):

    if request.method == "POST":
        temp = request.POST.get('hello_world_input')
        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list':hello_world_list})

class AccountCreateView(CreateView):
   model = User
   form_class = UserCreationForm
   success_url = reverse_lazy('accountapp:hello_world')
   template_name = 'accountapp/create.html' 

dcurator/accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>SignUp</h4>
        </div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

dcurator/accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %} 

<div style="border-radius: 1rem; margin: 2rem;text-align: center">
    <h1 style="font-family: 'Roboto', sans-serif">
        Hello World List!
    </h1>

    <form action="/account/hello_world/" method="post">
        {% csrf_token %}
        <div>
            <input type='text' name="hello_world_input">
        </div>
        <input type='submit' class="btn btn-primary" value="POST">
    </form>
    {% if hello_world_list %}
        {% for hello_world in hello_world_list %}
        <h4>
            {{ hello_world.text }}
        </h4>
        {% endfor %}
    {% endif %}
</div>

{% endblock %}

dcurator/accountapp/templates/accountapp/login.html
{%  extends 'base.html' %}
{% load bootstrap4 %}
{%  block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
{#                {{ form }}#}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>

{%  endblock %}

dcurator/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include "head.html" %}
<body style="font-family: 'NanumSquareR;">
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>
    
    {% include 'footer.html' %}
</body>
</html>

dcurator/templates/footer.html
<div class = dcurator_footer>
    <div class="pragmatic_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span> 
    </div>
    <div style="margin-top: 1rem;">
        <h6 class='dcurator_logo'>DCURATOR</h6>
    </div>
</div>

dcurator/templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>DCURATOR</title>
    <!-- bootstrap link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <!-- GOOGLE FONTS LINK -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Karla:wght@200&family=Roboto:wght@500&display=swap" rel="stylesheet">
    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{%  static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{%  static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{%  static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{%  static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
    </style>
</head>
<body>   
</body>
</html>

dcurator/templates/header.html
<div class='dcurator_header'>
    <div>
        <h1 class='dcurator_logo'>DCURATOR</h1>
    </div>
    <div>
        <span>nav1</span>
        <span>nav2</span>
        <span>nav3</span>
        {%  if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
            <span>login</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>logout</span>
        </a>
       {%  endif %}
    </div>
</div>